"""RACI rows for AC Brands. v7, after Alvin's edits on the page, 2026-08-06.

Tuple: (Function, Activity, [A...], R, [C...], [I...], Transition, Source, Notes)
  A = answers for the outcome. It can be shared, so A is a list.
  R = does the work. Exactly one per row.
  Transition = "" | "OPS" | "PDS" is the incoming seat that absorbs R on hire.
  Open seats never hold A or R; a vacancy cannot be accountable.
  Partner organisations can hold R (they do the work) but never A.

Sources are the SJ-OS repo (paths relative to /home/user/SJ-OS), the AC Brands
landing hub (relative to /home/user/acb-thelanding, prefixed "acb-thelanding:"),
the 2026-07-30 leadership review, the 2026-07-27 email to Danielle, the two
specialist job descriptions, Alvin's corrections of 2026-07-31, and Alvin's
edits made directly on the published page on 2026-08-06.

v7 is the first version where the row data came back from the page rather than
going out to it. Alvin reassigned 83 rows and deleted eight. The pattern in his
edits: Danielle picks up A on the leadership-level calls (HR policy, finance,
brand and marketing content, claims), Nicole picks up the documentation and
regulatory gates plus all-channel ownership, and Alvin holds R on 55 of the
94 rows. Rows carrying a rewritten rationale say so in the note.
"""

POSITIONS = [
  ('AC', 'Ayesha Curry', 'Owner / Founder', 'filled'),
  ('DI', 'Danielle Iturbe', 'President', 'filled'),
  ('AB', 'Alvin Belt', 'VP of Operations', 'filled'),
  ('NI', 'Nicole Iturbe', 'Sr. Director, Consumer Strategy & Operations', 'filled'),
  ('OPS', 'Open seat', 'Operations Specialist', 'recruiting'),
  ('PDS', 'Open seat', 'Product Development Specialist', 'phased'),
  ('SS', 'Soraya Salgadoe', 'Marketing Manager', 'filled'),
  ('KL', 'Kate Le', 'Social Media Coordinator', 'filled'),
  ('EH', 'Erin Hover', 'Creative Director', 'contractor'),
  ('IT', 'Ivy Tan', 'Creative / Design Coordinator', 'filled'),
  ('JH', 'Jan Haeck', 'Packaging Engineer', 'contractor'),
  ('PC', 'Perrine Calvet', 'PD / R&D contractor, Milinyc', 'contractor'),
  ('PR', 'Pedrero Regulatory', 'External regulatory partner', 'partner'),
  ('IF', 'Ironclad Finance', 'Outsourced finance (Dan Bender)', 'partner'),
  ('CH', 'Calm HR', 'PEO and co-employer', 'partner'),
  ('WI', 'WITHIN', 'Digital marketing agency', 'partner'),
  ('TK', 'Teknologics', 'Web development', 'partner'),
  ('CI', 'Coastal Interactive', 'Managed IT service provider', 'partner'),
]

ROWS = [

# ==== Product Development ====
  ('Product Development', 'Formula stage-gate progression through the PD Formula Tracker', ['PC'], 'AB', ['NI'], ['DI', 'SS', 'AC', 'OPS'], 'PDS', '.claude/skills/asana-pd-manager/references/role-map.md:16; .claude/skills/asana-pd-manager/SKILL.md:60; Alvin, 2026-07-31 (Coastal Interactive; PD visibility); Alvin, 2026-08-06 (page edits)', 'PD Lead holds technical sign-off on formula stage moves. Operator confirms every move (Rule 1 preview); reversals get a stronger intent check. Perrine and Soraya are never blank on a PD row - PD technical guidance and the marketing read both need visibility on every product decision.'),
  ('Product Development', 'Compatibility, stability, RIPT and PET decisions (pre-launch)', ['DI'], 'PC', ['AB', 'NI'], ['SS', 'AC', 'OPS', 'PDS'], '', '.claude/skills/asana-pd-manager/references/role-map.md:16; Alvin, 2026-07-31 (Coastal Interactive; PD visibility); Alvin, 2026-08-06 (page edits)', 'Perrine runs the testing and makes the technical call. Danielle answers for the outcome, which keeps a launch-gating test result in front of the President rather than inside the contractor relationship. Alvin and Nicole consulted. Worth a second look: the technical call and the accountability now sit with different people, and Perrine is external.'),
  ('Product Development', 'Packaging development with fillers and component vendors', ['AC'], 'AB', ['PC', 'DI', 'NI'], ['SS', 'JH', 'EH', 'OPS'], 'PDS', '.claude/skills/asana-pd-manager/references/role-map.md:16,23; Alvin, 2026-07-31 (role correction); Alvin, 2026-07-31 (Coastal Interactive; PD visibility); Alvin, 2026-08-06 (page edits)', 'Alvin runs packaging development with the fillers and component vendors. Ayesha answers for it as the founder whose name is on the pack. Perrine consulted where formula contact or compatibility is in play, Danielle and Nicole on the commercial and documentation side. Transitions to the PD Specialist on hire. Worth a second look: Erin and Jan are the two people who actually execute packaging and artwork, and both are now informed rather than accountable.'),
  ('Product Development', 'Direction-changing PD decisions (launch scope, supplier change, kill calls)', ['DI'], 'AB', ['NI', 'PC'], ['AC', 'SS'], '', '.claude/skills/asana-pd-manager/references/role-map.md:17,18; Alvin, 2026-07-31 (Coastal Interactive; PD visibility)', 'President approves. PD Consult is final-line approver alongside the President. Perrine and Soraya are never blank on a PD row - PD technical guidance and the marketing read both need visibility on every product decision.'),
  ('Product Development', 'Founder approval on brand-line moves', ['AC'], 'DI', ['NI', 'AB'], ['PC', 'SS'], '', '.claude/skills/asana-pd-manager/references/role-map.md:19; Alvin, 2026-07-31 (Coastal Interactive; PD visibility); Alvin, 2026-08-06 (page edits)', 'Founder gate. Danielle carries the ask to Ayesha and answers for getting it there; Ayesha holds the decision. Perrine and Soraya stay informed, as on every product decision.'),
  ('Product Development', 'PD signal intake from meetings and supplier email, plus PD status reporting', ['AB'], 'AB', ['PC', 'NI'], ['DI', 'SS', 'OPS'], 'PDS', '.claude/skills/fireflies-asana-bridge/SKILL.md:287; .claude/skills/outlook-plm-bridge/SKILL.md:191; .claude/skills/sjs-status-reporter/SKILL.md:331,385; Alvin, 2026-07-31 (Coastal Interactive; PD visibility); Alvin, 2026-08-06 (page edits)', 'Alvin is the named approver on Flow D formula-approval decisions and classifies every meeting item. Covers the three PD hub dashboards. A and R both AB. Perrine and Soraya are never blank on a PD row - PD technical guidance and the marketing read both need visibility on every product decision.'),
  ('Product Development', 'Reformulation triggered by a Quality or Regulatory reverse-handoff', ['DI'], 'AB', ['NI', 'PC'], ['SS', 'PDS', 'AC'], '', '.claude/skills/asana-pd-manager/references/role-map.md:16; .claude/skills/capa-coordinator/SKILL.md:85; Alvin, 2026-07-31 (Coastal Interactive; PD visibility); Alvin, 2026-08-06 (page edits)', 'Alvin drives the reformulation once Quality or Regulatory hands it back. Danielle answers for it, since a reformulation moves cost, timeline and claims at once. Perrine and Nicole consulted on the technical root cause. The handoff rides the root-cause approval, so there is no separate gate.'),
  ('Product Development', 'Document control: specifications, dielines, artwork versions, BOMs, landed-cost integrity', ['NI'], 'AB', ['EH', 'JH', 'PC'], ['SS', 'DI'], 'PDS', 'SharePoint: Sweet July Skin - Product Development Specialist - Job Description.docx; Alvin, 2026-07-31 (Coastal Interactive; PD visibility); Alvin, 2026-08-06 (page edits)', "Documentation quality is Nicole's gate. The PD Specialist JD names document control as a core responsibility, so this row transitions on hire. Perrine and Soraya are never blank on a PD row - PD technical guidance and the marketing read both need visibility on every product decision."),

# ==== Operations & Supply Chain ====
  ('Operations & Supply Chain', 'Vendor master data, onboarding (NDA + W9 gate), sourcing and performance scorecards', ['AB'], 'AB', ['PC', 'NI', 'SS'], ['DI', 'AC'], 'OPS', '.claude/skills/purchasing-manager/SKILL.md:42,46,75,154,158; Alvin, 2026-08-06 (page edits)', 'PLM vendor record created only after Operations approves at 2D. First-contact routing varies by vendor_type (SKILL.md:50-56) but the approval gate does not. A and R both AB.'),
  ('Operations & Supply Chain', 'Purchase order lifecycle: placement, acknowledgement variance, close and discrepancy', ['AB'], 'AB', ['NI'], ['PDS', 'PC', 'SS'], 'OPS', '.claude/skills/purchasing-manager/SKILL.md:108,116,140,248; Alvin, 2026-08-06 (page edits)', 'Six sub-flows from draft to close, plus Job 10 discrepancy investigation. Every gate is Operations. A and R both AB.'),
  ('Operations & Supply Chain', 'Goods receipt on PD-linked purchase orders', ['PC'], 'AB', ['NI'], ['SS', 'PDS'], 'OPS', '.claude/skills/purchasing-manager/SKILL.md:130; Alvin, 2026-08-06 (page edits)', 'PD owns the close on PD-linked receipts; Purchasing carries the receipt signal only. The one Ops row where accountability sits off the VP seat.'),
  ('Operations & Supply Chain', 'Three-way reconciliation across PLM, Shopify and Logiwa', ['AB'], 'AB', ['NI'], [], 'OPS', '.claude/skills/inventory-manager/SKILL.md:68', 'Operations decides the correction direction, usually trusting Logiwa as physical reality. A and R both AB.'),
  ('Operations & Supply Chain', 'Vendor invoice classification and cost capture (five HITL gates)', ['AB'], 'AB', ['NI', 'SS', 'IF', 'PDS'], ['DI'], 'OPS', '.claude/skills/purchasing-manager/SKILL.md:234,235,238; Alvin, 2026-07-31 (external partners); Alvin, 2026-08-06 (page edits)', 'Operator confirms cost_category, regulatory_driver, linked SKU and multi-home routing before any PLM write, and approves the dispute branch. A and R both AB. Ironclad consulted - classified invoices land in their ledger.'),
  ('Operations & Supply Chain', 'Inventory position keeping, batch creation on receipt and the location ledger', ['AB'], 'AB', ['PC', 'NI'], ['PDS'], 'OPS', '.claude/skills/inventory-manager/SKILL.md:18,52,60; Alvin, 2026-08-06 (page edits)', 'Ex-Ops-Coordinator scope. Alvin took inventory under the 2026-07-17 interim split. A and R both AB.'),
  ('Operations & Supply Chain', 'Adjustments, write-offs and return dispositions', ['AB'], 'AB', ['PC', 'NI'], [], 'OPS', '.claude/skills/inventory-manager/SKILL.md:94; Alvin, 2026-08-06 (page edits)', 'Operations approves. Near-expiry write-offs wait on the quality call first. A and R both AB.'),
  ('Operations & Supply Chain', 'S&OP: forecast, inventory targets and buy recommendations', ['AB'], 'AB', ['NI', 'PDS'], ['DI'], 'OPS', '.claude/skills/supply-demand-planner/SKILL.md:30-52; .claude/skills/supply-demand-planner/references/plm-schema-additions.md:139; Alvin, 2026-08-06 (page edits)', 'Operations approves; plm-assistant executes the SQL. Four intertwined jobs on one person. A and R both AB.'),
  ('Operations & Supply Chain', 'Inbound freight, customs, duty and carrier claims', ['AB'], 'AB', ['NI'], ['PC'], 'OPS', '.claude/skills/logistics-manager/SKILL.md:59,186; .claude/skills/logistics-manager/forms/international-dtc-shipment.md:11; Alvin, 2026-08-06 (page edits)', 'Nothing created or updated until Operations signs off. Ex-Ops-Coordinator logistics scope, now Alvin. HCT and Impress origin Asia so customs is routine. A and R both AB.'),
  ('Operations & Supply Chain', 'Daily DTC order operations and the Logiwa report parse', ['NI'], 'NI', ['AB'], [], 'OPS', '.claude/skills/ayesha-weekly-briefing/SKILL.md:123; .claude/skills/oc3pl-order-manager/SKILL.md:109,191', 'Ex-Ops-Coordinator scope. Nicole covers order management and OC3PL under the 2026-07-17 interim split. A and R both NI.'),
  ('Operations & Supply Chain', 'Pre-ship out-of-stock holds from the shortage sheet', ['NI'], 'AB', ['SS'], ['DI', 'AC'], 'OPS', '.claude/skills/oc3pl-order-manager/SKILL.md:201; .claude/skills/ayesha-weekly-briefing/SKILL.md:123; Alvin, 2026-08-06 (page edits)', 'Order-side holds sit with Nicole; SKU-level shortage routing belongs to inventory-manager, so Alvin does the work.'),
  ('Operations & Supply Chain', 'Retailer ASN / EDI 856 and routing-guide compliance (Ulta DC, Amazon Vendor)', ['NI'], 'AB', [], ['DI'], 'OPS', '.claude/skills/logistics-manager/SKILL.md:80; .claude/skills/purchasing-manager/SKILL.md:55', 'Operations or Order Ops reviews. UBM launch June 2026 is the deadline driver on this lane.'),
  ('Operations & Supply Chain', 'Production scheduling with manufacturing partners', ['AB'], 'AB', ['PC', 'NI'], ['DI', 'SS'], 'OPS', 'SharePoint: Sweet July Skin - Operations Specialist - Job Description.docx; Leadership Business Review 2026-07-30 35:18; Alvin, 2026-08-06 (page edits)', 'Named in the Ops Specialist JD under Planning & Special Projects. Today Alvin coordinates KDC scheduling directly. A and R both AB until the seat is filled.'),

# ==== Quality ====
  ('Quality', 'Customer complaint intake, classification and first response', ['NI'], 'AB', ['PC'], ['DI', 'AC', 'SS', 'OPS'], 'PDS', '.claude/skills/complaint-and-event-handler/SKILL.md:20,53; Alvin, 2026-08-06 (page edits)', 'HITL on every write. Operator approves classification plus first response. Gate moved to Nicole as the final quality check per Leadership Business Review 2026-07-30 25:18-26:01.'),
  ('Quality', 'Complaint trend analysis by SKU and batch', ['AB'], 'AB', ['PC', 'NI'], ['OPS', 'SS', 'DI', 'AC'], 'PDS', '.claude/skills/quality-manager/references/role-map.md:15; Alvin, 2026-08-06 (page edits)', 'Alvin answers for the trend read and runs it. Perrine and Nicole consulted on the technical pattern. Monthly trend review per the 30 July leadership review. Transitions to the PD Specialist on hire.'),
  ('Quality', 'NCR and CAPA lifecycle, intake through close (SKN-OPS-001)', ['AB'], 'AB', ['PC', 'NI'], ['DI', 'OPS'], 'PDS', '.claude/skills/capa-coordinator/SKILL.md:54,136; .claude/skills/capa-coordinator/references/ncr-procedure.md:135; .claude/skills/capa-coordinator/references/skn-ops-001.md:64,102; Alvin, 2026-08-06 (page edits)', 'Alvin approves intake, both action plans, conversion, root cause, verification, effectiveness and close. Six SOP phases on one seat. Perrine consulted on technical root cause, Nicole on documentation quality. Transitions to the PD Specialist on hire.'),
  ('Quality', 'Lab finding intake and OOS / OOT classification (SKN-OPS-006)', ['NI'], 'AB', ['PC'], ['OPS', 'SS', 'DI'], 'PDS', '.claude/skills/quality-lab-coordinator/SKILL.md:48,56; Alvin, 2026-08-06 (page edits)', 'Operator approves intake and the single-versus-systemic classification. Gate moved to Nicole per Leadership Business Review 2026-07-30 25:35-25:50. Perrine consults on the technical call.'),
  ('Quality', 'Vendor quality flag and scorecard signal back to Purchasing', ['AB'], 'AB', ['PC', 'NI', 'OPS'], ['DI'], 'PDS', '.claude/skills/quality-lab-coordinator/SKILL.md:76; .claude/skills/quality-lab-coordinator/references/vendor-scorecard-signal.md:103; Alvin, 2026-08-06 (page edits)', 'Alvin approves any vendor flag and the scorecard band. Perrine and Nicole consulted, and the incoming Operations Specialist can stage a flag but not commit it. Transitions to the PD Specialist on hire.'),
  ('Quality', 'Batch hold and release (SKN-OPS-007)', ['NI'], 'AB', ['PC'], ['DI', 'OPS'], 'PDS', '.claude/skills/batch-lifecycle-tracker/references/batch-lifecycle-procedure.md:208; .claude/skills/batch-lifecycle-tracker/SKILL.md:86; Alvin, 2026-08-06 (page edits)', 'QA Lead approves every hold and every release. No exceptions at v5.4. Releases need a CAPA close or clean retest plus QA Lead judgment. A moved from Perrine to Nicole per Leadership Business Review 2026-07-30 25:35-26:01. Perrine consults on the technical basis.'),
  ('Quality', 'In-market stability testing decisions (PET, accelerated, real-time)', ['PC'], 'AB', ['NI', 'DI'], ['OPS', 'SS'], 'PDS', '.claude/skills/batch-lifecycle-tracker/SKILL.md:71,94; Alvin, 2026-08-06 (page edits)', 'Technical testing call stays with Perrine as the R&D and quality technical advisor. Operator approves schedule edits. Per Leadership Business Review 2026-07-30 25:18-25:35 the process gate moved to Nicole but the technical judgment did not.'),
  ('Quality', 'Near-expiry batch disposition at the 30-day threshold', ['NI'], 'AB', ['PC'], ['OPS', 'DI', 'SS'], 'PDS', '.claude/skills/batch-lifecycle-tracker/SKILL.md:71,94; Alvin, 2026-08-06 (page edits)', 'Disposition is a quality gate, so it moves to Nicole. Posts back to inventory before any write-off.'),
  ('Quality', 'Serious adverse event triage and recall kickoff (SKN-OPS-002, SKN-OPS-003)', ['AB'], 'AB', ['PC', 'NI', 'PR'], ['DI', 'AC', 'OPS', 'PDS', 'SS'], '', '.claude/skills/complaint-and-event-handler/SKILL.md:85,89,95; .claude/skills/regulatory-manager/references/pedrero-contacts.md:9,13,21; Alvin, 2026-08-06 (page edits)', 'The strictest gate in the suite: explicit approval at every step, §4.A through §4.F each a separate gate. Operator decides severity, team and whether external reporting is needed. A and R both AB. Stays with Alvin as Reg Lead, given the legal and agency exposure. Nicole consults. Pedrero Regulatory holds the binding external review; consult-only internally, with no Asana access and no internal authority, so the Reg Lead gate stays in-house.'),
  ('Quality', 'SOP ratification, annual review and cross-cutting quality tasks', ['AB'], 'AB', ['PC', 'NI', 'DI', 'SS'], [], '', '.claude/skills/quality-manager/SKILL.md:66,135; .claude/skills/quality-manager/references/sop-catalog.md:120; .claude/skills/quality-manager/references/qos-thresholds.md:52; Alvin, 2026-08-06 (page edits)', 'Alvin approves every ratification, review outcome, cross-cutting task and quality-of-service threshold. SOP section 7 names a QA Manager for this and that seat does not exist, so the framework owner holds it. Perrine, Nicole, Danielle and Soraya consulted.'),
  ('Quality', 'Quality dashboard publish to the landing hub', ['AB'], 'AB', ['PC', 'NI'], ['OPS', 'DI', 'SS'], 'PDS', '.claude/skills/quality-status-reporter/SKILL.md:78; Alvin, 2026-08-06 (page edits)', 'Alvin approves the commit before push and answers for what the dashboard says. Nicole and Perrine consulted on the content. Never commit without confirmation. Transitions to the PD Specialist on hire.'),
  ('Quality', 'Final quality check on product and documentation across every function', ['NI'], 'AB', ['PC', 'SS'], ['AC', 'DI', 'OPS'], 'PDS', 'Leadership Business Review 2026-07-30 25:35-26:01; Alvin, 2026-08-06 (page edits)', 'The cross-function gate. Nicole holds it, verbatim from the 30 July review: "anything related to quality of service or quality of product will go through Nicole\'s eyes as sort of that final quality check." Alvin runs the checks into that gate until the PD Specialist absorbs the work.'),
  ('Quality', 'Quality management system framework and monthly quality-trend review', ['AB'], 'AB', ['PC', 'NI'], ['DI', 'SS', 'PDS', 'OPS'], '', 'Leadership Business Review 2026-07-30 25:18-26:17; Alvin, 2026-08-06 (page edits)', 'Alvin owns the framework and runs it. Nicole and Perrine consulted. Monthly trend review so recurring issues, the pump issue being the worked example, can drive packaging or formula decisions. Target: implemented by end of Q3.'),

# ==== Regulatory & Compliance ====
  ('Regulatory & Compliance', 'Pre-launch ingredient list review gate (SKN-OPS-008)', ['NI'], 'AB', ['PC', 'PR'], ['DI', 'OPS'], 'PDS', '.claude/skills/claims-il-and-label-keeper/SKILL.md:50; .claude/skills/claims-il-and-label-keeper/references/il-claims-label-procedure.md:62; .claude/skills/regulatory-manager/references/pedrero-contacts.md:9,13,21; Alvin, 2026-08-06 (page edits)', 'Alvin runs the review and approves intake; Nicole holds the gate as the final quality and documentation check, so the review and the approval are separate people for the first time. Pedrero holds the binding external call, consult-only internally with no Asana access. Transitions to the PD Specialist on hire.'),
  ('Regulatory & Compliance', 'Pedrero engagement and send approval', ['AB'], 'AB', ['PC', 'PR', 'NI'], ['PDS', 'OPS', 'DI'], '', '.claude/skills/claims-il-and-label-keeper/SKILL.md:60; .claude/skills/regulatory-manager/SKILL.md:140; .claude/skills/regulatory-manager/references/pedrero-contacts.md:9,13,21; Alvin, 2026-08-06 (page edits)', 'Reg Lead approves every Pedrero send; Operator hits send manually. Both roles are Alvin. A and R both AB. Pedrero Regulatory holds the binding external review; consult-only internally, with no Asana access and no internal authority, so the Reg Lead gate stays in-house.'),
  ('Regulatory & Compliance', 'Claim substantiation and new-claim defensibility', ['DI'], 'AB', ['SS', 'PC', 'EH', 'AC', 'PR', 'NI'], [], 'PDS', '.claude/skills/claims-il-and-label-keeper/SKILL.md:97; .claude/skills/claims-il-and-label-keeper/references/il-claims-label-procedure.md:29; Alvin, 2026-07-31 (role correction); .claude/skills/regulatory-manager/references/pedrero-contacts.md:9,13,21; Alvin, 2026-08-06 (page edits)', 'Alvin runs the substantiation path and the Pedrero stage. Danielle answers for the claim, which is the right level given a claim is a commercial and legal commitment. The procedure exists because new claims from marketing or the founder used to skip Pedrero sign-off, so Soraya, Ayesha, Erin, Perrine and Nicole are consulted rather than bypassed. Transitions to the PD Specialist on hire.'),
  ('Regulatory & Compliance', 'Label artwork archive, IL cross-check and label-law checks (Pantone, Canada, Quebec, 19-state toxics)', ['NI'], 'AB', ['PC', 'JH', 'AC', 'PR', 'EH'], ['DI', 'SS', 'OPS'], 'PDS', '.claude/skills/claims-il-and-label-keeper/SKILL.md:85; .claude/skills/claims-il-and-label-keeper/references/il-claims-label-procedure.md:93; Alvin, 2026-07-31 (role correction); .claude/skills/regulatory-manager/references/pedrero-contacts.md:9,13,21; Alvin, 2026-08-06 (page edits)', 'Alvin runs the IL cross-check and the label-law passes. Nicole approves the archive entry, so the documentation gate and the work are separate people. Erin and Jan consulted as the people producing the artwork under review, Pedrero on the external read. Transitions to the PD Specialist on hire.'),
  ('Regulatory & Compliance', 'Reformulation claim bridge when a SKU reformulates without QIL parity', ['DI'], 'AB', ['NI', 'PR', 'PC', 'SS'], ['OPS', 'AC'], 'PDS', '.claude/skills/claims-il-and-label-keeper/references/il-claims-label-procedure.md:281; .claude/skills/regulatory-manager/references/pedrero-contacts.md:9,13,21; Alvin, 2026-08-06 (page edits)', 'Alvin makes the QIL recovery ask to the prior manufacturer and rebuilds the claim set. Danielle answers for what is claimed on the reformulated SKU. Perrine and Soraya consulted on the formulation and the marketing read, Pedrero and Nicole on the review. Transitions to the PD Specialist on hire.'),
  ('Regulatory & Compliance', 'Retailer attestation responses (Sephora, Ulta, Whole Foods, Credo)', ['NI'], 'AB', ['PC', 'AC', 'PR'], ['DI', 'SS', 'OPS'], 'PDS', '.claude/skills/claims-il-and-label-keeper/SKILL.md:105; .claude/skills/regulatory-manager/SKILL.md:122; Alvin, 2026-07-31 (role correction); .claude/skills/regulatory-manager/references/pedrero-contacts.md:9,13,21; Alvin, 2026-08-06 (page edits)', 'Alvin prepares and sends the retailer submission after Pedrero approval. Nicole approves it as the documentation gate. Ayesha consulted, since retailer clean-standard positioning is a brand claim. Transitions to the PD Specialist on hire.'),
  ('Regulatory & Compliance', 'MoCRA registrations, state filings and Leaping Bunny renewal', ['AB'], 'AB', ['PR', 'NI', 'PC'], ['SS', 'DI'], 'PDS', '.claude/skills/regulatory-manager/SKILL.md:114,367; .claude/skills/regulatory-manager/references/pedrero-contacts.md:9,13,21; Alvin, 2026-08-06 (page edits)', 'Operator approves the filing draft; Reg Lead approves every registration record write. Both roles are Alvin. A and R both AB. Pedrero Regulatory holds the binding external review; consult-only internally, with no Asana access and no internal authority, so the Reg Lead gate stays in-house.'),
  ('Regulatory & Compliance', 'SAE and recall agency filings, including the 15-day MoCRA clock (SKN-OPS-009)', ['AB'], 'AB', ['PC', 'NI', 'PR'], ['DI', 'AC', 'SS', 'OPS'], 'PDS', '.claude/skills/adverse-event-and-recall-reporter/SKILL.md:65,108; .claude/skills/regulatory-manager/references/pedrero-contacts.md:9,13,21; Alvin, 2026-08-06 (page edits)', 'Two distinct gates per filing - Pedrero send approval and agency submission approval - both held by Alvin. Statutory clock with no named backup. A and R both AB. Pedrero Regulatory holds the binding external review; consult-only internally, with no Asana access and no internal authority, so the Reg Lead gate stays in-house.'),
  ('Regulatory & Compliance', 'Regulatory fan-out routing and the regulatory dashboard publish', ['AB'], 'AB', ['PC', 'PR', 'NI'], ['OPS', 'SS', 'DI'], 'PDS', '.claude/skills/regulatory-manager/SKILL.md:60; .claude/skills/regulatory-status-reporter/SKILL.md:90; .claude/skills/regulatory-manager/references/pedrero-contacts.md:9,13,21; Alvin, 2026-08-06 (page edits)', 'Two gates per fan-out (Operator for the routing call, Reg Lead for task creation), both Alvin. Operator approves the dashboard commit before push. A and R both AB. Pedrero Regulatory holds the binding external review; consult-only internally, with no Asana access and no internal authority, so the Reg Lead gate stays in-house.'),
  ('Regulatory & Compliance', 'Pedrero engagement letter, scope and renewal', ['AB'], 'AB', ['PR', 'DI', 'NI'], ['PDS'], '', '.claude/skills/regulatory-manager/references/pedrero-contacts.md:50; Alvin, 2026-07-31 (external partners); Alvin, 2026-08-06 (page edits)', 'The engagement letter governs scope, retainer, response windows and dispute resolution. Annual renewal. A and R both AB - the only person managing the regulatory partner relationship.'),

# ==== Retail & Wholesale ====
  ('Retail & Wholesale', 'Retailer and reseller first contact', ['NI'], 'NI', ['AB'], ['DI', 'OPS', 'SS'], '', '.claude/skills/purchasing-manager/SKILL.md:55; acb-thelanding: data/links.json; Alvin, 2026-08-06 (page edits)', "First-contact owner for retailer, promotional_goods and accessories vendor types is the Sr. Director Consumer Strategy & Ops. A and R both NI. Consistent with Nicole's all-channel accountability."),
  ('Retail & Wholesale', 'Wholesale pipeline and new retail partner development', ['NI'], 'NI', ['AB', 'SS'], ['DI', 'AC', 'OPS', 'PDS'], '', 'acb-thelanding: data/links.json (Sales & Commerce lead: "TBD (wholesale)"); Alvin, 2026-07-31 (marketing, wholesale and web); Alvin, 2026-08-06 (page edits)', 'Hub left wholesale unowned. Resolved to Nicole with all-channel accountability. A and R both Nicole - no second pair of eyes on new-partner decisions.'),
  ('Retail & Wholesale', 'Retail price architecture and the pricing matrix', ['NI'], 'NI', ['DI', 'SS', 'PC', 'AB'], ['AC', 'OPS', 'PDS'], '', 'acb-thelanding: data/links.json (Sales & Commerce / Retail Price Architecture, SJS Pricing Matrix); Alvin, 2026-07-31 (marketing, wholesale and web); Alvin, 2026-08-06 (page edits)', 'Nicole owns the pricing matrix and does the work. Live on the hub with retail, wholesale and subscription prices and margin colouring. Alvin and Danielle consulted, since it ties to the margin framework and the walk-away call.'),
  ('Retail & Wholesale', 'Retailer promo calendar (Sephora, Ulta) and promo planning', ['NI'], 'NI', ['AB', 'KL', 'SS', 'DI'], ['AC', 'OPS', 'PDS'], '', 'acb-thelanding: data/links.json (Market Intelligence / Promo Landscape); Alvin, 2026-07-31 (marketing, wholesale and web); Alvin, 2026-08-06 (page edits)', 'Nicole runs promo planning and answers for the channel commitment. Promo Landscape tracks the Sephora and Ulta calendar. Soraya, Kate, Alvin and Danielle consulted.'),

# ==== Marketing & Brand ====
  ('Marketing & Brand', 'Social listening and comp brand monitoring (TikTok, IG, Pinterest, retailer new arrivals)', ['SS'], 'KL', ['DI'], ['AC', 'AB', 'NI'], '', '.claude/skills/sjs-comp-intel/references/team-ownership.md:34,40-44; Alvin, 2026-07-31 (role correction); Alvin, 2026-08-06 (page edits)', 'Kate owns social listening tool maintenance, query hygiene and the weekly retailer new-arrivals scan. Soraya answers for what the signal means for the brand. Danielle consulted.'),
  ('Marketing & Brand', 'Brand guideline custody (fonts, colors, logos, voice)', ['DI'], 'SS', ['IT', 'AC', 'NI', 'EH'], ['KL'], '', '.claude/skills/sweet-july-skin-brand/SKILL.md:1; references/architecture/system_map.md:157; Alvin, 2026-07-31 (role correction); acb-thelanding: data/links.json; Alvin, 2026-08-06 (page edits)', 'Every output-producing skill defers here for canonical brand spec; no skill carries its own copy. Danielle answers for the brand standard, Soraya maintains it as the function lead, Erin consulted as Creative Director. Ayesha consulted, the brand carries her name.'),
  ('Marketing & Brand', 'Annual team holiday communications (11 sends across 3 templates)', ['DI'], 'AB', [], ['NI', 'SS', 'KL', 'IT', 'OPS', 'PDS', 'AC'], '', '.claude/skills/ac-brands-holiday-comms/SKILL.md:26,165; Alvin, 2026-08-06 (page edits)', 'Sends from alvin@ac-brands.com with the team on BCC, including the Outlook calendar sync and the annual maintenance. Alvin runs it; Danielle answers for what goes out to the team.'),
  ('Marketing & Brand', 'Operational special projects: labels, PR seeding, sampling', ['NI'], 'NI', ['SS', 'KL', 'EH', 'DI', 'AB'], ['AC', 'PDS'], '', "SharePoint: Sweet July Skin - Operations Specialist - Job Description.docx; Email to Danielle 2026-07-27 'Proposed Ops Positions'; Alvin, 2026-07-31 (role correction); Alvin, 2026-08-06 (page edits)", 'Named in the Ops Specialist JD, and in the 27 July email as making sure product is where it needs to be for launches, promos, PR seeding and sampling. Nicole owns it and runs it. Alvin, Soraya, Kate, Erin and Danielle consulted. The transition marker was cleared, so this stays with Nicole rather than moving to the Operations Specialist on hire.'),
  ('Marketing & Brand', 'Campaign direction and seasonal brand moments', ['DI'], 'SS', ['EH', 'KL', 'NI', 'AC'], ['AB', 'OPS', 'PDS'], '', 'Alvin, 2026-07-31 (role correction); .claude/skills/sjs-margin-walk-away/SKILL.md:93; Alvin, 2026-08-06 (page edits)', 'Added 2026-07-31. Campaign direction was absent from the matrix, which is why the President and the Founder had almost no Marketing presence. Danielle answers for it - Soraya reports to her and the margin sources already have her approving every repricing and channel call. Ayesha consulted on brand moments.'),
  ('Marketing & Brand', 'Editorial and content calendar', ['DI'], 'SS', ['EH', 'NI', 'KL'], ['AB', 'AC'], '', 'acb-thelanding: data/links.json (Marketing / Owned Channels); Alvin, 2026-07-31 (marketing, wholesale and web); Alvin, 2026-08-06 (page edits)', 'Soraya runs the editorial and content calendar; Danielle answers for it. Editorial Calendar is a named tool under Owned Channels. Kate, Erin and Nicole consulted.'),
  ('Marketing & Brand', 'Email marketing: Klaviyo flows and campaign sends', ['DI'], 'SS', ['KL', 'NI', 'WI'], ['AB', 'AC'], '', 'acb-thelanding: data/links.json (Marketing / Klaviyo Performance); Alvin, 2026-07-31 (marketing, wholesale and web); Alvin, 2026-08-06 (page edits)', 'Soraya owns Klaviyo flows and campaign sends, with WITHIN consulted as the agency doing execution. Danielle answers for the channel. Klaviyo Performance is a named tool on the hub.'),
  ('Marketing & Brand', 'Paid media: Meta, Google and channel spend', ['DI'], 'SS', ['AB', 'NI', 'WI'], ['AC'], '', 'acb-thelanding: data/links.json (Marketing / Paid Media Dashboard); Alvin, 2026-07-31 (marketing, wholesale and web); Alvin, 2026-08-06 (page edits)', 'Soraya runs paid spend across Meta and Google, with WITHIN consulted on execution. Danielle answers for it. Alvin consulted on spend against margin floors. Quarterly business reviews with WITHIN, the most recent on 20 July.'),
  ('Marketing & Brand', 'Social media content and publishing', ['SS', 'DI'], 'KL', ['EH', 'IT'], ['AC'], '', 'acb-thelanding: data/links.json (Marketing / Social Media Dashboard); Alvin, 2026-07-31 (marketing, wholesale and web); Alvin, 2026-08-06 (page edits)', 'Distinct from social listening, which Soraya answers for. Kate does the publishing. Soraya and Danielle share the accountability.'),
  ('Marketing & Brand', 'Influencer and earned media programs', ['SS', 'DI'], 'KL', ['NI'], ['AB', 'AC'], '', 'acb-thelanding: data/links.json; Alvin, 2026-07-31 (marketing, wholesale and web); Alvin, 2026-08-06 (page edits)', 'Kate runs the programs. Soraya and Danielle share the accountability, since this is brand-facing and founder-adjacent. Nicole consulted. The physical seeding logistics sit on the Operations special-projects row.'),
  ('Marketing & Brand', 'WITHIN agency relationship and quarterly business reviews', ['SS', 'NI'], 'SS', ['AB', 'DI'], ['AC', 'KL'], '', 'Alvin, 2026-07-31 (marketing, wholesale and web); Alvin, 2026-08-06 (page edits)', 'Soraya runs the relationship and the quarterly reviews, with Nicole sharing the accountability. WITHIN holds most of our digital marketing execution, so the engagement is a single point of dependency, the same shape as the other external parties.'),

# ==== Creative ====
  ('Creative', 'Creative direction on packaging, artwork and brand visuals', ['EH', 'AC'], 'EH', ['IT', 'SS', 'NI', 'JH', 'DI'], ['AB', 'PDS', 'PC', 'OPS'], '', '.claude/skills/asana-pd-manager/references/role-map.md:22; Alvin, 2026-07-31 (role correction); Alvin, 2026-08-06 (page edits)', 'Erin owns packaging, artwork and brand visuals and does the work. Ayesha shares the accountability, the brand carries her name. Erin is a contractor with no internal backup. Jan, Ivy, Nicole, Soraya and Danielle consulted.'),
  ('Creative', 'Packaging and artwork execution', ['EH'], 'JH', ['PC', 'DI', 'NI', 'SS'], ['AB', 'AC', 'PDS', 'OPS'], '', '.claude/skills/asana-pd-manager/references/role-map.md:23; .claude/skills/sjs-comp-intel/references/team-ownership.md:79; Alvin, 2026-07-31 (role correction); Alvin, 2026-08-06 (page edits)', 'Jan is the creative contractor under Erin. Title differs between sources - Packaging Engineer in one, creative contractor in the other. Erin holds technical authority; Jan executes. Both contractors.'),
  ('Creative', 'Creative Requests intake and design coordination', ['DI'], 'IT', ['EH', 'SS', 'NI', 'JH'], ['AB'], '', '.claude/skills/sjs-status-reporter/SKILL.md:352; .claude/skills/asana-pd-manager/references/role-map.md:24; Alvin, 2026-07-31 (role correction); Alvin, 2026-08-06 (page edits)', 'Ivy owns the Creative Requests project and coordinates the queue; Danielle answers for intake priority. Ivy supports Erin and Jan. Nicole, Jan, Erin and Soraya consulted.'),

# ==== Ecommerce & DTC ====
  ('Ecommerce & DTC', 'Shopify revenue and channel position read', ['NI'], 'NI', ['SS', 'AB'], ['DI', 'PDS', 'AC'], 'OPS', 'connections.md:7; context/about-business.md:5; acb-thelanding: data/links.json; Alvin, 2026-07-31 (marketing, wholesale and web); Alvin, 2026-08-06 (page edits)', 'Nicole is accountable for all channels, DTC, Amazon and wholesale, and holds the revenue read. Alvin and Soraya consulted, Danielle informed. This was the last row on the matrix with no owner. Transitions to the Operations Specialist on hire.'),
  ('Ecommerce & DTC', 'Daily DTC fulfillment KPIs and the SJ Shipping Dashboard', ['NI'], 'NI', ['AB'], ['DI', 'SS'], 'OPS', '.claude/skills/oc3pl-order-manager/SKILL.md:61,191; .claude/skills/ayesha-weekly-briefing/SKILL.md:123; Alvin, 2026-08-06 (page edits)', 'Ex-Ops-Coordinator scope, now Nicole per the interim split. A and R both NI.'),
  ('Ecommerce & DTC', 'Channel operations and promo setup across DTC, UBM and Amazon', ['NI'], 'NI', ['SS', 'KL', 'AB'], ['DI', 'PDS'], 'OPS', 'SharePoint: Sweet July Skin - Operations Specialist - Job Description.docx; acb-thelanding: data/links.json; Alvin, 2026-07-31 (marketing, wholesale and web); Alvin, 2026-08-06 (page edits)', 'Named in the Ops Specialist JD under Order Management and Channel Operations. Nicole holds the channel relationship and runs the setup until the Operations Specialist absorbs it. Alvin and Kate consulted.'),
  ('Ecommerce & DTC', 'Proactive reships and fulfillment-issue resolution', ['NI'], 'NI', ['AB'], [], 'OPS', 'SharePoint: Sweet July Skin - Operations Specialist - Job Description.docx', 'JD wording: resolve fulfillment issues "before a customer has to follow up." Sits inside Nicole\'s interim OC3PL coverage. A and R both NI.'),
  ('Ecommerce & DTC', 'Amazon channel management (FBA, AWD, Seller Central)', ['NI'], 'AB', ['SS'], ['DI', 'AC'], 'OPS', 'acb-thelanding: data/links.json (Sales & Commerce / Amazon Dashboard); Alvin, 2026-07-31 (marketing, wholesale and web)', 'Hub gave Amazon to Alvin; resolved to Nicole under all-channel accountability with Alvin doing the work. Inventory and inbound pipeline transition to the Ops Specialist.'),
  ('Ecommerce & DTC', 'Product detail page content and product copy', ['NI'], 'NI', ['PC', 'EH', 'IT', 'SS'], ['AB', 'DI', 'PDS'], 'OPS', 'acb-thelanding: data/links.json (Sales & Commerce / SJS Product Copy Database); Alvin, 2026-07-31 (marketing, wholesale and web); Alvin, 2026-08-06 (page edits)', 'Nicole owns product detail page content and copy. Product Copy Database is live from PLM and carries every claim, ingredient line, FAQ and Amazon title across DTC, Amazon and wholesale. Soraya, Perrine, Erin and Ivy consulted, because claims on a PDP are claims. Transitions to the Operations Specialist on hire.'),

# ==== Finance ====
  ('Finance', 'Margin architecture framework and quarterly portfolio review', ['AB'], 'AB', ['DI', 'NI', 'IF'], ['OPS', 'PDS', 'SS', 'AC', 'PC'], '', '.claude/skills/sjs-margin-architect/references/framework.md:209; .claude/skills/sjs-margin-portfolio-review/SKILL.md:1; Alvin, 2026-08-06 (page edits)', 'Framework reference plus the quarterly portfolio sweep and traffic-light report. A and R both AB.'),
  ('Finance', 'Monthly and quarterly vendor cost rollups', ['AB'], 'AB', ['IF', 'NI', 'PDS'], ['DI', 'SS'], 'OPS', '.claude/skills/regulatory-manager/SKILL.md:196; .claude/skills/purchasing-manager/SKILL.md:365; Alvin, 2026-07-31 (external partners); Alvin, 2026-08-06 (page edits)', 'regulatory-manager Jobs 8 and 9 read vendor_invoices directly; purchasing-manager has no rollup of its own. A and R both AB. Ironclad consulted - the rollup feeds their books.'),
  ('Finance', 'Accounts payable, bookkeeping and payroll', ['DI'], 'IF', ['AB'], [], '', 'Alvin, 2026-07-31 (external partners); Alvin, 2026-08-06 (page edits)', 'Ironclad Finance runs AP, bookkeeping and payroll; Dan Bender is the contact. Danielle answers for it, with Alvin consulted where the vendor-invoice pipeline and its five approval gates feed the books. No longer an unowned function.'),
  ('Finance', 'Month-end close and management reporting', ['DI'], 'IF', ['AB', 'NI'], ['AC'], '', 'Alvin, 2026-07-31 (external partners)', 'Ironclad Finance closes the books and produces the reporting; Dan Bender is the contact. Reporting accountability sits with the President.'),
  ('Finance', 'Annual budget and forecast consolidation', ['DI'], 'IF', ['AB', 'NI', 'SS'], ['AC'], '', 'Alvin, 2026-07-31 (external partners)', 'President answers for the budget. Operations and Consumer Strategy feed the operating and channel assumptions.'),
  ('Finance', 'Inventory valuation and cost of goods', ['AB'], 'IF', ['NI', 'PC'], ['DI', 'PDS', 'OPS'], '', 'Alvin, 2026-07-31 (external partners); .claude/skills/inventory-manager/SKILL.md:18; Alvin, 2026-08-06 (page edits)', 'Cost side, so accountability sits with Operations - it flows out of purchasing, receiving and the inventory ledger. Ironclad carries it into the books.'),

# ==== People & Admin ====
  ('People & Admin', 'Hiring the Operations Specialist and the PD Project Manager Specialist', ['AB'], 'NI', ['DI', 'CH'], ['AC'], '', 'decisions/log.md:52,58; context/priorities.md:3; Alvin, 2026-07-31 (external partners)', 'Both new roles report to Nicole. Decision owner recorded as Alvin, with Nicole on the two new roles once filled. Priority 1 of 2 this quarter. Calm HR runs the recruiting process once the RACI clears Danielle.'),
  ('People & Admin', 'Tool procurement, vendor renewals and shared-folder admin', ['AB', 'DI'], 'AB', ['NI'], ['SS', 'PDS', 'OPS'], '', '.claude/skills/sjs-comp-intel/references/team-ownership.md:50; .claude/skills/sjs-comp-intel/references/sequencing-plan.md:12; Alvin, 2026-08-06 (page edits)', 'Ex-Ops-Coordinator scope. Alvin carries it directly until the Operations Specialist starts, and answers for it alongside Danielle. Nicole consulted.'),
  ('People & Admin', 'Employee onboarding, offboarding and access deprovisioning', ['AB'], 'AB', ['DI', 'CI', 'CH'], ['NI'], '', '.claude/skills/asana-pd-manager/references/role-map.md:48-56; Alvin, 2026-07-31 (external partners); Alvin, 2026-07-31 (Coastal Interactive; PD visibility); Alvin, 2026-08-06 (page edits)', 'Alvin runs onboarding, offboarding and access deprovisioning and answers for it. Two partners split the execution and both are consulted: Calm HR on the employment side, Coastal Interactive on equipment and account provisioning. Danielle consulted. The departed-role-holder checklist in the PD role-map is the internal system-side counterpart.'),
  ('People & Admin', 'Operations Specialist recruiting', ['AB'], 'CH', ['DI', 'NI'], ['AC'], '', "Leadership Business Review 2026-07-30 52:48-53:17; Email to Danielle 2026-07-27 'Proposed Ops Positions'; Alvin, 2026-08-06 (page edits)", 'Prioritized first. Calm HR runs the search as the PEO; Alvin answers for the hire. Danielle: "we\'re going to prioritize the operations... Specialist." Reports to Nicole. Target in place before Q4. Salary band $72-90K.'),
  ('People & Admin', 'PD Specialist role definition and phased recruiting', ['AB'], 'NI', ['CH', 'DI'], ['AC'], '', "Leadership Business Review 2026-07-30 53:17-57:10; Email to Danielle 2026-07-27 'Proposed Ops Positions'; Alvin, 2026-08-06 (page edits)", 'Phased in after the Ops Specialist. Danielle scopes it as "air traffic control, holding people accountable" rather than strategy or ideation, and is adding trend-forecasting language to the JD. Reports to Nicole. Salary band $75-95K.'),
  ('People & Admin', 'SOP cleanup and operational prep before new-hire onboarding', ['AB'], 'AB', ['NI'], ['DI'], '', 'Leadership Business Review 2026-07-30 54:24-55:43, 1:00:32; Alvin, 2026-08-06 (page edits)', "Danielle's condition on the hire: clean up the system first so the role can function. Alvin does the cleanup and answers for it, with Nicole consulted."),
  ('People & Admin', 'Employee handbook and HR policy', ['DI'], 'CH', ['AB'], ['NI', 'AC'], '', 'Alvin, 2026-07-31 (external partners); Alvin, 2026-08-06 (page edits)', 'Calm HR drafts and maintains the handbook; Alvin is the liaison; Danielle answers for the policy. In flight as of 30 July and goes to legal review before implementation.'),
  ('People & Admin', 'Benefits administration and payroll processing', ['DI'], 'CH', ['IF', 'AB'], [], '', 'Alvin, 2026-07-31 (external partners); Alvin, 2026-08-06 (page edits)', 'Calm HR administers as co-employer. Danielle answers for it. Ironclad consulted where payroll hits the books, Alvin as the liaison.'),
  ('People & Admin', 'Employment compliance and separations', ['DI'], 'CH', ['AB'], [], '', 'Alvin, 2026-07-31 (external partners); Alvin, 2026-08-06 (page edits)', 'Calm HR runs the process with outside counsel where needed. Danielle answers for every separation, Alvin consulted as the liaison.'),

# ==== IT / Systems & Data ====
  ('IT / Systems & Data', 'PLM schema, write path, audit log and Supabase wiki custody', ['AB', 'NI'], 'AB', [], [], '', '.claude/skills/plm-assistant/SKILL.md:292; decisions/wiki-layer-audit-2026-07-29.md:52; Alvin, 2026-08-06 (page edits)', 'plm-assistant is the sole PLM writer and every write needs Operations sign-off. Alvin runs it, with Nicole sharing the accountability as the systems and tech owner. Job 0 wiki write-back has not fired since 2026-05-26.'),
  ('IT / Systems & Data', 'Landing hub publish and Netlify Function maintenance', ['AB'], 'AB', ['NI'], [], '', '.claude/skills/quality-status-reporter/SKILL.md:34-50; .claude/skills/quality-status-reporter/references/hub-integration.md:85; Alvin, 2026-08-06 (page edits)', 'All hub writes go through the landing-hub-publish Function behind an Operator gate. Deploy is commit-and-push only, never Netlify CLI. A and R both AB.'),
  ('IT / Systems & Data', 'Asana project, section, custom-field and connector configuration', ['AB'], 'AB', ['NI'], [], '', 'references/architecture/asana_task_contract.md:227; connections.md:5-13; Alvin, 2026-07-31 (Coastal Interactive; PD visibility); Alvin, 2026-08-06 (page edits)', 'An unresolvable role-holder is surfaced for Alvin to decide, not dropped. Seven tool domains registered; iMessage still not connected. A and R both AB. Coastal Interactive consulted on identity, access and integration plumbing behind the connectors.'),
  ('IT / Systems & Data', 'Skill suite authorship, audit and versioning', ['AB'], 'AB', ['TK'], ['NI'], '', 'decisions/skills-architecture-tracker.md:4; decisions/log.md:31,45; Alvin, 2026-08-06 (page edits)', 'Owner recorded as Alvin Belt across the architecture decisions. Priority 2 of 2 this quarter. A and R both AB.'),
  ('IT / Systems & Data', 'The 23 scheduled Routines and their HITL gates', ['AB'], 'AB', ['TK'], ['NI'], '', 'scheduled-prompts/weekly-pd-update.md:91; scheduled-prompts/sjs-purchasing-monthly-rollup-and-snapshot.md:79; Alvin, 2026-08-06 (page edits)', 'Nothing commits until Alvin says go. Same pattern across all 23 Routines, including the ones that fire unattended on a schedule. A and R both AB.'),
  ('IT / Systems & Data', 'RACI and role framework across Operations and PD', ['AB'], 'AB', ['DI', 'NI'], [], '', 'Leadership Business Review 2026-07-30 52:12-52:39; Alvin, 2026-08-06 (page edits)', 'Alvin owns the framework and builds it, with Nicole and Danielle consulted. Danielle gives final review before it goes to Calm HR to start recruiting.'),
  ('IT / Systems & Data', 'Website platform, Shopify storefront and web releases', ['DI', 'NI'], 'NI', ['SS', 'EH', 'IT', 'TK'], ['AB'], '', 'Alvin, 2026-07-31 (marketing, wholesale and web); Alvin, 2026-08-06 (page edits)', 'Danielle and Nicole share the accountability; Nicole runs it as the systems and tech owner. Teknologics consulted as the web development partner, Erin and Ivy on visual design, Soraya on merchandising and content. Alvin informed.'),
  ('IT / Systems & Data', 'Web and digital systems ownership, including the Teknologics engagement', ['NI'], 'NI', ['TK', 'AB', 'SS'], ['AC', 'DI'], '', 'Alvin, 2026-07-31 (marketing, wholesale and web); Alvin, 2026-08-06 (page edits)', 'Nicole owns the web and digital stack outright, including the Teknologics engagement. Scoped to web and digital rather than the whole IT function: the PLM, Asana, hub-publish and Routine rows still sit with Alvin. Confirm whether that should widen.'),
  ('IT / Systems & Data', 'Back-end IT infrastructure, identity and endpoint management', ['AB'], 'CI', ['NI'], ['DI'], '', 'Alvin, 2026-07-31 (Coastal Interactive; PD visibility)', 'Coastal Interactive is the managed service provider and handles the higher-level IT and systems work. Alvin is the liaison and answers for it. Distinct from the web and digital stack, which sits with Danielle and Nicole.'),
  ('IT / Systems & Data', 'Equipment procurement, onboarding and asset lifecycle', ['DI'], 'CI', ['NI', 'CH', 'AB'], [], 'OPS', 'Alvin, 2026-07-31 (Coastal Interactive; PD visibility); Alvin, 2026-08-06 (page edits)', 'Coastal Interactive provisions and recovers equipment. Danielle answers for it. Pairs with the Calm HR employment side on every start and every exit. Transitions to the Operations Specialist on hire.'),
  ('IT / Systems & Data', 'Coastal Interactive managed-service engagement and escalation', ['AB'], 'AB', ['CI', 'NI', 'DI'], [], '', 'Alvin, 2026-07-31 (Coastal Interactive; PD visibility)', 'A and R both Alvin - he is the sole liaison to the IT managed-service partner. Same single-point shape as the other partner relationships.'),
]
