"""RACI rows for AC Brands. v5 — the whole business, not just what has a skill.

Tuple: (Function, Activity, A, R, [C...], [I...], Transition, Source, Notes)
  A = answers for the outcome. R = does the work. One of each per row.
  Transition = "" | "OPS" | "PDS" — the incoming seat that absorbs R on hire.
  Open seats never hold A or R; a vacancy cannot be accountable.
  Partner organisations can hold R — they do the work — but never A.

Sources are the SJ-OS repo (paths relative to /home/user/SJ-OS), the AC Brands
landing hub (paths relative to /home/user/acb-thelanding, prefixed "acb-thelanding:"),
the 2026-07-30 leadership review, the 2026-07-27 email to Danielle, the two specialist
job descriptions, and Alvin's corrections of 2026-07-31.

v5 adds real Marketing, Retail & Wholesale and Web activities that have no skill
behind them, sourced from the hub's function definitions. Nicole takes accountability
for all channels; Soraya for Marketing; Danielle for web. WITHIN and Teknologics join
as partner organisations. Nothing on the matrix is unowned any more.
"""

POSITIONS = [
  ('AC', 'Ayesha Curry', 'Owner / Founder', 'filled'),
  ('DI', 'Danielle Iturbe', 'President', 'filled'),
  ('AB', 'Alvin Belt', 'VP of Operations', 'filled'),
  ('NI', 'Nicole Iturbe', 'Sr. Director, Consumer Strategy & Operations', 'filled'),
  ('OPS', 'Open seat', 'Operations Specialist', 'recruiting'),
  ('PDS', 'Open seat', 'Product Development Specialist', 'phased'),
  ('SS', 'Soraya Salgadoe', 'Marketing Manager', 'filled'),
  ('KL', 'Kate Le', 'Social Media Coordinator', 'filled'),
  ('EH', 'Erin Hover', 'Creative Director', 'contractor'),
  ('IT', 'Ivy Tan', 'Creative / Design Coordinator', 'filled'),
  ('JH', 'Jan Haeck', 'Packaging Engineer', 'contractor'),
  ('PC', 'Perrine Calvet', 'PD / R&D contractor, Milinyc', 'contractor'),
  ('PR', 'Pedrero Regulatory', 'External regulatory partner', 'partner'),
  ('IF', 'Ironclad Finance', 'Outsourced finance (Dan Bender)', 'partner'),
  ('CH', 'Calm HR', 'PEO and co-employer', 'partner'),
  ('WI', 'WITHIN', 'Digital marketing agency', 'partner'),
  ('TK', 'Teknologics', 'Web development', 'partner'),
]

ROWS = [

# ==== Product Development ====
  ('Product Development', 'Formula stage-gate progression through the PD Formula Tracker', 'PC', 'AB', ['NI'], ['DI'], 'PDS', '.claude/skills/asana-pd-manager/references/role-map.md:16; .claude/skills/asana-pd-manager/SKILL.md:60', 'PD Lead holds technical sign-off on formula stage moves. Operator confirms every move (Rule 1 preview); reversals get a stronger intent check.'),
  ('Product Development', 'Compatibility, stability, RIPT and PET decisions (pre-launch)', 'PC', 'PC', ['AB'], ['NI'], '', '.claude/skills/asana-pd-manager/references/role-map.md:16', 'PD Lead owns the technical call outright. A and R the same person, and PC is an external contractor.'),
  ('Product Development', 'Packaging development with fillers and component vendors', 'EH', 'JH', ['PC', 'AB', 'IT'], ['DI', 'AC'], '', '.claude/skills/asana-pd-manager/references/role-map.md:16,23; Alvin, 2026-07-31 (role correction)', 'PD Lead owns packaging dev calls; Jan executes packaging and artwork under Erin. Both are contractors. Erin is the lead technical authority on packaging and artwork and answers for the outcome; Jan executes under her. Perrine consults where formula contact or compatibility is in play. Both Erin and Jan are contractors.'),
  ('Product Development', 'Direction-changing PD decisions (launch scope, supplier change, kill calls)', 'DI', 'AB', ['NI', 'PC'], ['AC'], '', '.claude/skills/asana-pd-manager/references/role-map.md:17,18', 'President approves. PD Consult is final-line approver alongside the President.'),
  ('Product Development', 'Founder approval on brand-line moves', 'AC', 'AB', ['DI', 'NI'], [], '', '.claude/skills/asana-pd-manager/references/role-map.md:19', 'Founder gate. Ayesha receives weekly PD signal through the Friday briefing.'),
  ('Product Development', 'PD signal intake from meetings and supplier email, plus PD status reporting', 'AB', 'AB', ['PC', 'NI'], ['DI'], 'PDS', '.claude/skills/fireflies-asana-bridge/SKILL.md:287; .claude/skills/outlook-plm-bridge/SKILL.md:191; .claude/skills/sjs-status-reporter/SKILL.md:331,385', 'Alvin is the named approver on Flow D formula-approval decisions and classifies every meeting item. Covers the three PD hub dashboards. A and R both AB.'),
  ('Product Development', 'Reformulation triggered by a Quality or Regulatory reverse-handoff', 'PC', 'AB', ['NI'], ['DI'], '', '.claude/skills/asana-pd-manager/references/role-map.md:16; .claude/skills/capa-coordinator/SKILL.md:85', 'PD Lead is cross-flagged for any PD-side reformulation. Reformulation handoff rides the root-cause approval - no separate gate.'),
  ('Product Development', 'Document control: specifications, dielines, artwork versions, BOMs, landed-cost integrity', 'NI', 'AB', ['EH', 'JH', 'PC'], [], 'PDS', 'SharePoint: Sweet July Skin - Product Development Specialist - Job Description.docx', "Documentation quality is Nicole's gate. The PD Specialist JD names document control as a core responsibility, so this row transitions on hire."),

# ==== Operations & Supply Chain ====
  ('Operations & Supply Chain', 'Vendor master data, onboarding (NDA + W9 gate), sourcing and performance scorecards', 'AB', 'AB', ['PC', 'NI', 'SS'], [], 'OPS', '.claude/skills/purchasing-manager/SKILL.md:42,46,75,154,158', 'PLM vendor record created only after Operations approves at 2D. First-contact routing varies by vendor_type (SKILL.md:50-56) but the approval gate does not. A and R both AB.'),
  ('Operations & Supply Chain', 'Purchase order lifecycle: placement, acknowledgement variance, close and discrepancy', 'AB', 'AB', ['PC'], [], 'OPS', '.claude/skills/purchasing-manager/SKILL.md:108,116,140,248', 'Six sub-flows from draft to close, plus Job 10 discrepancy investigation. Every gate is Operations. A and R both AB.'),
  ('Operations & Supply Chain', 'Goods receipt on PD-linked purchase orders', 'PC', 'AB', ['NI'], [], '', '.claude/skills/purchasing-manager/SKILL.md:130', 'PD owns the close on PD-linked receipts; Purchasing carries the receipt signal only. The one Ops row where accountability sits off the VP seat.'),
  ('Operations & Supply Chain', 'Three-way reconciliation across PLM, Shopify and Logiwa', 'AB', 'AB', ['NI'], [], 'OPS', '.claude/skills/inventory-manager/SKILL.md:68', 'Operations decides the correction direction, usually trusting Logiwa as physical reality. A and R both AB.'),
  ('Operations & Supply Chain', 'Vendor invoice classification and cost capture (five HITL gates)', 'AB', 'AB', ['NI', 'SS', 'IF'], ['DI'], 'OPS', '.claude/skills/purchasing-manager/SKILL.md:234,235,238; Alvin, 2026-07-31 (external partners)', 'Operator confirms cost_category, regulatory_driver, linked SKU and multi-home routing before any PLM write, and approves the dispute branch. A and R both AB. Ironclad consulted - classified invoices land in their ledger.'),
  ('Operations & Supply Chain', 'Inventory position keeping, batch creation on receipt and the location ledger', 'AB', 'AB', ['PC'], ['NI'], 'OPS', '.claude/skills/inventory-manager/SKILL.md:18,52,60', 'Ex-Ops-Coordinator scope. Alvin took inventory under the 2026-07-17 interim split. A and R both AB.'),
  ('Operations & Supply Chain', 'Adjustments, write-offs and return dispositions', 'AB', 'AB', ['PC'], [], 'OPS', '.claude/skills/inventory-manager/SKILL.md:94', 'Operations approves. Near-expiry write-offs wait on the quality call first. A and R both AB.'),
  ('Operations & Supply Chain', 'S&OP: forecast, inventory targets and buy recommendations', 'AB', 'AB', ['NI'], ['DI'], 'OPS', '.claude/skills/supply-demand-planner/SKILL.md:30-52; .claude/skills/supply-demand-planner/references/plm-schema-additions.md:139', 'Operations approves; plm-assistant executes the SQL. Four intertwined jobs on one person. A and R both AB.'),
  ('Operations & Supply Chain', 'Inbound freight, customs, duty and carrier claims', 'AB', 'AB', [], ['PC'], 'OPS', '.claude/skills/logistics-manager/SKILL.md:59,186; .claude/skills/logistics-manager/forms/international-dtc-shipment.md:11', 'Nothing created or updated until Operations signs off. Ex-Ops-Coordinator logistics scope, now Alvin. HCT and Impress origin Asia so customs is routine. A and R both AB.'),
  ('Operations & Supply Chain', 'Daily DTC order operations and the Logiwa report parse', 'NI', 'NI', ['AB'], [], 'OPS', '.claude/skills/ayesha-weekly-briefing/SKILL.md:123; .claude/skills/oc3pl-order-manager/SKILL.md:109,191', 'Ex-Ops-Coordinator scope. Nicole covers order management and OC3PL under the 2026-07-17 interim split. A and R both NI.'),
  ('Operations & Supply Chain', 'Pre-ship out-of-stock holds from the shortage sheet', 'NI', 'AB', [], [], 'OPS', '.claude/skills/oc3pl-order-manager/SKILL.md:201; .claude/skills/ayesha-weekly-briefing/SKILL.md:123', 'Order-side holds sit with Nicole; SKU-level shortage routing belongs to inventory-manager, so Alvin does the work.'),
  ('Operations & Supply Chain', 'Retailer ASN / EDI 856 and routing-guide compliance (Ulta DC, Amazon Vendor)', 'NI', 'AB', [], ['DI'], 'OPS', '.claude/skills/logistics-manager/SKILL.md:80; .claude/skills/purchasing-manager/SKILL.md:55', 'Operations or Order Ops reviews. UBM launch June 2026 is the deadline driver on this lane.'),
  ('Operations & Supply Chain', 'Production scheduling with manufacturing partners', 'AB', 'AB', ['PC', 'NI'], [], 'OPS', 'SharePoint: Sweet July Skin - Operations Specialist - Job Description.docx; Leadership Business Review 2026-07-30 35:18', 'Named in the Ops Specialist JD under Planning & Special Projects. Today Alvin coordinates KDC scheduling directly. A and R both AB until the seat is filled.'),

# ==== Quality ====
  ('Quality', 'Customer complaint intake, classification and first response', 'NI', 'AB', ['PC'], [], 'PDS', '.claude/skills/complaint-and-event-handler/SKILL.md:20,53', 'HITL on every write. Operator approves classification plus first response. A and R both AB. Gate moved to Nicole as the final quality check per Leadership Business Review 2026-07-30 25:18-26:01.'),
  ('Quality', 'Complaint trend analysis by SKU and batch', 'NI', 'AB', ['PC'], [], 'PDS', '.claude/skills/quality-manager/references/role-map.md:15', 'Voice of Customer holds gates on complaint classification and complaint-driven escalations. Nicole already held this gate; monthly trend review formalizes it per Leadership Business Review 2026-07-30 26:02-26:17.'),
  ('Quality', 'NCR and CAPA lifecycle, intake through close (SKN-OPS-001)', 'NI', 'AB', ['PC'], ['DI'], 'PDS', '.claude/skills/capa-coordinator/SKILL.md:54,136; .claude/skills/capa-coordinator/references/ncr-procedure.md:135; .claude/skills/capa-coordinator/references/skn-ops-001.md:64,102', 'Operator approves intake and both action plans; QA Lead approves conversion, root cause, verification, effectiveness and close. Six SOP phases, one external contractor on every technical gate. A moved from Perrine to Nicole per Leadership Business Review 2026-07-30 25:18-25:50. Perrine consults on technical root cause.'),
  ('Quality', 'Lab finding intake and OOS / OOT classification (SKN-OPS-006)', 'NI', 'AB', ['PC'], [], 'PDS', '.claude/skills/quality-lab-coordinator/SKILL.md:48,56', 'Operator approves intake and the single-versus-systemic classification. A and R both AB. Gate moved to Nicole per Leadership Business Review 2026-07-30 25:35-25:50. Perrine consults on the technical call.'),
  ('Quality', 'Vendor quality flag and scorecard signal back to Purchasing', 'NI', 'AB', ['PC'], [], 'PDS', '.claude/skills/quality-lab-coordinator/SKILL.md:76; .claude/skills/quality-lab-coordinator/references/vendor-scorecard-signal.md:103', 'QA Lead approves any vendor flag and the scorecard band. Operator can stage but not commit. A moved from Perrine to Nicole per Leadership Business Review 2026-07-30 25:18-25:50. Perrine consults.'),
  ('Quality', 'Batch hold and release (SKN-OPS-007)', 'NI', 'AB', ['PC'], ['DI'], 'PDS', '.claude/skills/batch-lifecycle-tracker/references/batch-lifecycle-procedure.md:208; .claude/skills/batch-lifecycle-tracker/SKILL.md:86', 'QA Lead approves every hold and every release. No exceptions at v5.4. Releases need a CAPA close or clean retest plus QA Lead judgment. A moved from Perrine to Nicole per Leadership Business Review 2026-07-30 25:35-26:01. Perrine consults on the technical basis.'),
  ('Quality', 'In-market stability testing decisions (PET, accelerated, real-time)', 'PC', 'AB', ['NI'], [], 'PDS', '.claude/skills/batch-lifecycle-tracker/SKILL.md:71,94', 'Technical testing call stays with Perrine as the R&D and quality technical advisor. Operator approves schedule edits. Per Leadership Business Review 2026-07-30 25:18-25:35 the process gate moved to Nicole but the technical judgment did not.'),
  ('Quality', 'Near-expiry batch disposition at the 30-day threshold', 'NI', 'AB', ['PC'], [], 'PDS', '.claude/skills/batch-lifecycle-tracker/SKILL.md:71,94', 'Disposition is a quality gate, so it moves to Nicole. Posts back to inventory before any write-off.'),
  ('Quality', 'Serious adverse event triage and recall kickoff (SKN-OPS-002, SKN-OPS-003)', 'AB', 'AB', ['PC', 'NI', 'PR'], ['DI', 'AC'], '', '.claude/skills/complaint-and-event-handler/SKILL.md:85,89,95; .claude/skills/regulatory-manager/references/pedrero-contacts.md:9,13,21', 'The strictest gate in the suite: explicit approval at every step, §4.A through §4.F each a separate gate. Operator decides severity, team and whether external reporting is needed. A and R both AB. Stays with Alvin as Reg Lead — legal and agency exposure. Nicole consults. Pedrero Regulatory holds the binding external review; consult-only internally, with no Asana access and no internal authority, so the Reg Lead gate stays in-house.'),
  ('Quality', 'SOP ratification, annual review and cross-cutting quality tasks', 'NI', 'AB', ['PC'], [], '', '.claude/skills/quality-manager/SKILL.md:66,135; .claude/skills/quality-manager/references/sop-catalog.md:120; .claude/skills/quality-manager/references/qos-thresholds.md:52', 'QA Lead approves every ratification, review outcome, cross-cutting task and QoS threshold task. SOP §7 names a QA Manager for this; that seat is vacant and Perrine is filling it. Gate moved to Nicole per Leadership Business Review 2026-07-30 25:18-25:50.'),
  ('Quality', 'Quality dashboard publish to the landing hub', 'NI', 'AB', ['PC'], [], 'PDS', '.claude/skills/quality-status-reporter/SKILL.md:78', 'Operator approves the commit before push. Never commit without confirmation. A and R both AB. Nicole gates the content; Alvin retains the publish mechanics. Per Leadership Business Review 2026-07-30 26:02-26:17.'),
  ('Quality', 'Final quality check on product and documentation across every function', 'NI', 'NI', ['AB', 'PC', 'SS', 'EH'], ['DI', 'AC'], '', 'Leadership Business Review 2026-07-30 25:35-26:01', 'The new cross-function gate. Verbatim: "anything related to quality of service or quality of product will go through Nicole\'s eyes as sort of that final quality check... Even with each function having or being the primary owner, we\'ll still have that quality gate." A and R both NI.'),
  ('Quality', 'Quality management system framework and monthly quality-trend review', 'AB', 'NI', ['PC'], ['DI'], '', 'Leadership Business Review 2026-07-30 25:18-26:17', 'Alvin owns the overall framework; Nicole runs it. Monthly trend review so recurring issues (the pump issue was the worked example) can drive packaging or formula decisions. Target: implemented by end of Q3.'),

# ==== Regulatory & Compliance ====
  ('Regulatory & Compliance', 'Pre-launch ingredient list review gate (SKN-OPS-008)', 'AB', 'AB', ['PC', 'PR'], ['NI'], 'PDS', '.claude/skills/claims-il-and-label-keeper/SKILL.md:50; .claude/skills/claims-il-and-label-keeper/references/il-claims-label-procedure.md:62; .claude/skills/regulatory-manager/references/pedrero-contacts.md:9,13,21', 'Operator approves intake. Reg Lead is the same person at v6.6, so the gate fires twice against one person. Pedrero holds the binding external call. A and R both AB. Pedrero Regulatory holds the binding external review; consult-only internally, with no Asana access and no internal authority, so the Reg Lead gate stays in-house.'),
  ('Regulatory & Compliance', 'Pedrero engagement and send approval', 'AB', 'AB', ['PC', 'PR'], [], '', '.claude/skills/claims-il-and-label-keeper/SKILL.md:60; .claude/skills/regulatory-manager/SKILL.md:140; .claude/skills/regulatory-manager/references/pedrero-contacts.md:9,13,21', 'Reg Lead approves every Pedrero send; Operator hits send manually. Both roles are Alvin. A and R both AB. Pedrero Regulatory holds the binding external review; consult-only internally, with no Asana access and no internal authority, so the Reg Lead gate stays in-house.'),
  ('Regulatory & Compliance', 'Claim substantiation and new-claim defensibility', 'AB', 'AB', ['SS', 'PC', 'EH', 'AC', 'PR'], ['DI'], 'PDS', '.claude/skills/claims-il-and-label-keeper/SKILL.md:97; .claude/skills/claims-il-and-label-keeper/references/il-claims-label-procedure.md:29; Alvin, 2026-07-31 (role correction); .claude/skills/regulatory-manager/references/pedrero-contacts.md:9,13,21', 'Operator approves the path; Reg Lead approves the Pedrero stage. The procedure exists because new claims from marketing or the founder used to skip Pedrero sign-off. A and R both AB. The procedure exists because new claims from marketing or the founder used to skip Pedrero sign-off, so both are consulted rather than bypassed. Pedrero Regulatory holds the binding external review; consult-only internally, with no Asana access and no internal authority, so the Reg Lead gate stays in-house.'),
  ('Regulatory & Compliance', 'Label artwork archive, IL cross-check and label-law checks (Pantone, Canada, Quebec, 19-state toxics)', 'EH', 'AB', ['PC', 'JH', 'NI', 'AC', 'PR'], ['DI'], '', '.claude/skills/claims-il-and-label-keeper/SKILL.md:85; .claude/skills/claims-il-and-label-keeper/references/il-claims-label-procedure.md:93; Alvin, 2026-07-31 (role correction); .claude/skills/regulatory-manager/references/pedrero-contacts.md:9,13,21', 'Operator approves each pass outcome; Reg Lead approves any archive entry. Creative produces the artwork under review. Erin answers for the artwork being right as lead technical authority. Alvin runs the IL cross-check and the label-law passes and holds the Reg Lead gate on archive entries, so the regulatory approval and the artwork authority are separate people. Pedrero Regulatory holds the binding external review; consult-only internally, with no Asana access and no internal authority, so the Reg Lead gate stays in-house.'),
  ('Regulatory & Compliance', 'Reformulation claim bridge when a SKU reformulates without QIL parity', 'AB', 'PC', ['NI', 'PR'], [], '', '.claude/skills/claims-il-and-label-keeper/references/il-claims-label-procedure.md:281; .claude/skills/regulatory-manager/references/pedrero-contacts.md:9,13,21', 'Reg Lead approves the QIL recovery ask to the prior manufacturer; PD Lead does the formulation work. Pedrero Regulatory holds the binding external review; consult-only internally, with no Asana access and no internal authority, so the Reg Lead gate stays in-house.'),
  ('Regulatory & Compliance', 'Retailer attestation responses (Sephora, Ulta, Whole Foods, Credo)', 'AB', 'AB', ['NI', 'PC', 'AC', 'PR'], ['DI'], 'PDS', '.claude/skills/claims-il-and-label-keeper/SKILL.md:105; .claude/skills/regulatory-manager/SKILL.md:122; Alvin, 2026-07-31 (role correction); .claude/skills/regulatory-manager/references/pedrero-contacts.md:9,13,21', 'Reg Lead approves the retailer submission after Pedrero approval. Voice of Customer consults where customer-perceived attributes matter. A and R both AB. Ayesha consulted - retailer clean-standard positioning is a brand claim. Pedrero Regulatory holds the binding external review; consult-only internally, with no Asana access and no internal authority, so the Reg Lead gate stays in-house.'),
  ('Regulatory & Compliance', 'MoCRA registrations, state filings and Leaping Bunny renewal', 'AB', 'AB', ['PR'], ['PC', 'SS'], 'PDS', '.claude/skills/regulatory-manager/SKILL.md:114,367; .claude/skills/regulatory-manager/references/pedrero-contacts.md:9,13,21', 'Operator approves the filing draft; Reg Lead approves every registration record write. Both roles are Alvin. A and R both AB. Pedrero Regulatory holds the binding external review; consult-only internally, with no Asana access and no internal authority, so the Reg Lead gate stays in-house.'),
  ('Regulatory & Compliance', 'SAE and recall agency filings, including the 15-day MoCRA clock (SKN-OPS-009)', 'AB', 'AB', ['PC', 'NI', 'PR'], ['DI', 'AC'], '', '.claude/skills/adverse-event-and-recall-reporter/SKILL.md:65,108; .claude/skills/regulatory-manager/references/pedrero-contacts.md:9,13,21', 'Two distinct gates per filing - Pedrero send approval and agency submission approval - both held by Alvin. Statutory clock with no named backup. A and R both AB. Pedrero Regulatory holds the binding external review; consult-only internally, with no Asana access and no internal authority, so the Reg Lead gate stays in-house.'),
  ('Regulatory & Compliance', 'Regulatory fan-out routing and the regulatory dashboard publish', 'AB', 'AB', ['PC', 'PR'], ['NI'], '', '.claude/skills/regulatory-manager/SKILL.md:60; .claude/skills/regulatory-status-reporter/SKILL.md:90; .claude/skills/regulatory-manager/references/pedrero-contacts.md:9,13,21', 'Two gates per fan-out (Operator for the routing call, Reg Lead for task creation), both Alvin. Operator approves the dashboard commit before push. A and R both AB. Pedrero Regulatory holds the binding external review; consult-only internally, with no Asana access and no internal authority, so the Reg Lead gate stays in-house.'),
  ('Regulatory & Compliance', 'Pedrero engagement letter, scope and renewal', 'AB', 'AB', ['PR', 'DI'], ['NI'], '', '.claude/skills/regulatory-manager/references/pedrero-contacts.md:50; Alvin, 2026-07-31 (external partners)', 'The engagement letter governs scope, retainer, response windows and dispute resolution. Annual renewal. A and R both AB - the only person managing the regulatory partner relationship.'),

# ==== Retail & Wholesale ====
  ('Retail & Wholesale', 'Retailer and reseller first contact', 'NI', 'NI', ['AB'], ['DI'], '', '.claude/skills/purchasing-manager/SKILL.md:55; acb-thelanding: data/links.json', "First-contact owner for retailer, promotional_goods and accessories vendor types is the Sr. Director Consumer Strategy & Ops. A and R both NI. Consistent with Nicole's all-channel accountability."),
  ('Retail & Wholesale', 'Retail channel launch programs: UBM cohort positioning, price ladder, Amazon Vendor', 'NI', 'AB', ['SS'], ['DI'], '', '.claude/skills/purchasing-manager/SKILL.md:55; .claude/skills/sjs-retail-intel/SKILL.md:52; .claude/skills/logistics-manager/SKILL.md:80; acb-thelanding: data/links.json; Alvin, 2026-07-31 (marketing, wholesale and web)', 'UBM launch June 2026. Nicole holds the channel relationship; Alvin runs the positioning and outbound work. Hub lists wholesale as "Owned by TBD" (links.json, Sales & Commerce lead). Resolved to Nicole as part of all-channel accountability.'),
  ('Retail & Wholesale', 'Wholesale pipeline and new retail partner development', 'NI', 'NI', ['AB', 'SS'], ['DI', 'AC'], '', 'acb-thelanding: data/links.json (Sales & Commerce lead: "TBD (wholesale)"); Alvin, 2026-07-31 (marketing, wholesale and web)', 'Hub left wholesale unowned. Resolved to Nicole with all-channel accountability. A and R both Nicole - no second pair of eyes on new-partner decisions.'),
  ('Retail & Wholesale', 'Retail price architecture and the pricing matrix', 'NI', 'AB', ['DI', 'SS', 'PC'], ['AC'], '', 'acb-thelanding: data/links.json (Sales & Commerce / Retail Price Architecture, SJS Pricing Matrix); Alvin, 2026-07-31 (marketing, wholesale and web)', 'Live pricing matrix on the hub carries retail, wholesale and subscription prices with margin colouring. Ties to the margin framework, so Danielle consulted as the walk-away approver.'),
  ('Retail & Wholesale', 'Retailer promo calendar (Sephora, Ulta) and promo planning', 'NI', 'SS', ['AB', 'KL'], ['DI', 'AC'], '', 'acb-thelanding: data/links.json (Market Intelligence / Promo Landscape); Alvin, 2026-07-31 (marketing, wholesale and web)', 'Promo Landscape tracks the Sephora and Ulta promo calendar. Marketing runs the planning; Nicole answers for the channel commitment.'),

# ==== Marketing & Brand ====
  ('Marketing & Brand', 'Quarterly competitive teardowns across the five comp brands', 'SS', 'SS', ['KL', 'NI', 'DI'], ['AB', 'AC'], '', '.claude/skills/sjs-comp-intel/references/team-ownership.md:19,23-30; Alvin, 2026-07-31 (role correction)', 'Soraya owns teardown production and comp brand profile maintenance. A and R both SS. Danielle consulted rather than only receiving the finished teardown.'),
  ('Marketing & Brand', 'Quarterly teardown sign-off before circulation', 'AB', 'SS', ['NI'], ['DI'], '', '.claude/skills/sjs-comp-intel/references/team-ownership.md:65; .claude/skills/sjs-comp-intel/SKILL.md:50', 'Alvin signs off before it circulates to Danielle and the SJS brand team.'),
  ('Marketing & Brand', 'Monthly competitive trend digest and cross-stream signal routing', 'NI', 'NI', ['SS', 'KL', 'DI'], ['AB', 'AC'], '', '.claude/skills/sjs-comp-intel/references/team-ownership.md:3,9-15; Alvin, 2026-07-31 (role correction)', "Stream DRI owns digest production and the 'what it means for SJS' analytical layer. Named as the stream's heartbeat - first thing protected under capacity pressure. A and R both NI. Danielle consulted on the digest's read."),
  ('Marketing & Brand', 'Social listening and comp brand monitoring (TikTok, IG, Pinterest, retailer new arrivals)', 'KL', 'KL', ['SS', 'DI'], ['AC'], '', '.claude/skills/sjs-comp-intel/references/team-ownership.md:34,40-44; Alvin, 2026-07-31 (role correction)', 'Kate owns social listening tool maintenance, query hygiene and the weekly retailer new-arrivals scan. A and R both KL. Danielle consulted on what the social signal implies for brand.'),
  ('Marketing & Brand', 'Brand guideline custody (fonts, colors, logos, voice)', 'DI', 'EH', ['IT', 'SS', 'AC'], ['KL'], '', '.claude/skills/sweet-july-skin-brand/SKILL.md:1; references/architecture/system_map.md:157; Alvin, 2026-07-31 (role correction); acb-thelanding: data/links.json', 'Every output-producing skill defers here for canonical brand spec; no skill carries its own copy. President answers for brand custody; Creative Director maintains it. Ayesha consulted - the brand carries her name. Every output-producing skill defers here for canonical spec. Hub lists Brand & Creative as "Owned by Soraya" as function lead; custody accountability sits with the President per the 31 July correction. Both hold: Soraya runs the function, Danielle answers for the brand standard.'),
  ('Marketing & Brand', 'Annual team holiday communications (11 sends across 3 templates)', 'AB', 'AB', [], ['NI', 'DI', 'SS', 'KL', 'IT'], '', '.claude/skills/ac-brands-holiday-comms/SKILL.md:26,165', 'Sends from alvin@ac-brands.com with the team on BCC. Includes the Outlook calendar sync and annual maintenance. A and R both AB.'),
  ('Marketing & Brand', 'Weekly founder briefing, Slides 5 and 6', 'AB', 'AB', ['NI', 'PC'], ['DI', 'AC'], '', '.claude/skills/ayesha-weekly-briefing/SKILL.md:49,72', 'Alvin owns both Slide 5 (Business Operations) and Slide 6 PD-Ops content; Nicole co-authors Slide 6 with her core PD content. A and R both AB.'),
  ('Marketing & Brand', 'Operational special projects: labels, PR seeding, sampling', 'NI', 'AB', ['SS', 'KL', 'EH', 'DI'], ['AC'], 'OPS', "SharePoint: Sweet July Skin - Operations Specialist - Job Description.docx; Email to Danielle 2026-07-27 'Proposed Ops Positions'; Alvin, 2026-07-31 (role correction)", 'Named in the Ops Specialist JD, and in the email as making sure product is where it needs to be for launches, promos, PR seeding and sampling. Danielle consulted - PR seeding and sampling are brand-facing.'),
  ('Marketing & Brand', 'Campaign direction and seasonal brand moments', 'DI', 'SS', ['EH', 'KL', 'NI', 'AC'], ['AB'], '', 'Alvin, 2026-07-31 (role correction); .claude/skills/sjs-margin-walk-away/SKILL.md:93', 'Added 2026-07-31. Campaign direction was absent from the matrix, which is why the President and the Founder had almost no Marketing presence. Danielle answers for it - Soraya reports to her and the margin sources already have her approving every repricing and channel call. Ayesha consulted on brand moments.'),
  ('Marketing & Brand', 'Editorial and content calendar', 'SS', 'KL', ['EH', 'NI', 'DI'], ['AB', 'AC'], '', 'acb-thelanding: data/links.json (Marketing / Owned Channels); Alvin, 2026-07-31 (marketing, wholesale and web)', 'Hub lists Marketing as "Owned by TBD"; resolved to Soraya as Marketing Manager. Editorial Calendar is a named tool under Owned Channels.'),
  ('Marketing & Brand', 'Email marketing: Klaviyo flows and campaign sends', 'SS', 'WI', ['KL', 'NI', 'DI'], ['AB', 'AC'], '', 'acb-thelanding: data/links.json (Marketing / Klaviyo Performance); Alvin, 2026-07-31 (marketing, wholesale and web)', 'WITHIN runs most of our digital marketing including email execution. Soraya answers for the channel. Klaviyo Performance is a named tool on the hub.'),
  ('Marketing & Brand', 'Paid media: Meta, Google and channel spend', 'SS', 'WI', ['AB', 'NI', 'DI'], ['AC'], '', 'acb-thelanding: data/links.json (Marketing / Paid Media Dashboard); Alvin, 2026-07-31 (marketing, wholesale and web)', 'WITHIN is the digital marketing agency and runs paid execution. Alvin consulted on spend against margin floors. Quarterly business reviews with WITHIN - the most recent was 20 July.'),
  ('Marketing & Brand', 'Social media content and publishing', 'SS', 'KL', ['EH', 'IT', 'DI'], ['AC'], '', 'acb-thelanding: data/links.json (Marketing / Social Media Dashboard); Alvin, 2026-07-31 (marketing, wholesale and web)', 'Distinct from social listening, which Kate is accountable for. Here she does the publishing work and Soraya answers for the channel.'),
  ('Marketing & Brand', 'Influencer and earned media programs', 'SS', 'KL', ['DI', 'NI'], ['AB', 'AC'], '', 'acb-thelanding: data/links.json; Alvin, 2026-07-31 (marketing, wholesale and web)', 'Brand-facing and founder-adjacent, so Danielle consulted and Ayesha informed. The physical seeding logistics sit on the Operations special-projects row.'),
  ('Marketing & Brand', 'WITHIN agency relationship and quarterly business reviews', 'SS', 'SS', ['AB', 'NI', 'DI'], ['AC'], '', 'Alvin, 2026-07-31 (marketing, wholesale and web)', 'A and R both Soraya. WITHIN holds most of our digital marketing execution, so the engagement is a single point of dependency - same shape as the other five external parties.'),

# ==== Creative ====
  ('Creative', 'Creative direction on packaging, artwork and brand visuals', 'EH', 'EH', ['IT', 'SS', 'DI', 'AC'], ['AB'], '', '.claude/skills/asana-pd-manager/references/role-map.md:22; Alvin, 2026-07-31 (role correction)', 'Creative Director owns packaging, artwork and brand visuals. A and R both EH. Creative Director owns the direction as lead technical authority, and is a contractor. Danielle and Ayesha both consulted. A and R the same person - no second pair of eyes, and no internal backup either.'),
  ('Creative', 'Packaging and artwork execution', 'EH', 'JH', ['PC', 'IT'], ['AB', 'DI', 'AC'], '', '.claude/skills/asana-pd-manager/references/role-map.md:23; .claude/skills/sjs-comp-intel/references/team-ownership.md:79; Alvin, 2026-07-31 (role correction)', 'Jan is the creative contractor under Erin. Title differs between sources - Packaging Engineer in one, creative contractor in the other. Erin holds technical authority; Jan executes. Both contractors.'),
  ('Creative', 'Creative Requests intake and design coordination', 'IT', 'IT', ['EH', 'SS', 'DI'], ['AB'], '', '.claude/skills/sjs-status-reporter/SKILL.md:352; .claude/skills/asana-pd-manager/references/role-map.md:24; Alvin, 2026-07-31 (role correction)', 'Creative Requests Asana project owner is Ivy, Editorial/Design team. Ivy supports Erin and Jan. A and R both IT. Danielle consulted on intake priority.'),

# ==== Ecommerce & DTC ====
  ('Ecommerce & DTC', 'Shopify revenue and channel position read', 'NI', 'AB', ['SS'], ['DI'], '', 'connections.md:7; context/about-business.md:5; acb-thelanding: data/links.json; Alvin, 2026-07-31 (marketing, wholesale and web)', 'Nicole is accountable for all channels - DTC, Amazon and wholesale - with Alvin consulted and Danielle informed. This was the last row on the matrix with no owner; it now has one.'),
  ('Ecommerce & DTC', 'Daily DTC fulfillment KPIs and the SJ Shipping Dashboard', 'NI', 'NI', ['AB'], [], 'OPS', '.claude/skills/oc3pl-order-manager/SKILL.md:61,191; .claude/skills/ayesha-weekly-briefing/SKILL.md:123', 'Ex-Ops-Coordinator scope, now Nicole per the interim split. A and R both NI.'),
  ('Ecommerce & DTC', 'Channel operations and promo setup across DTC, UBM and Amazon', 'NI', 'AB', ['SS', 'KL'], ['DI'], 'OPS', 'SharePoint: Sweet July Skin - Operations Specialist - Job Description.docx; acb-thelanding: data/links.json; Alvin, 2026-07-31 (marketing, wholesale and web)', "Named in the Ops Specialist JD under Order Management & Channel Operations. Nicole holds the channel relationship. Part of Nicole's all-channel accountability."),
  ('Ecommerce & DTC', 'Proactive reships and fulfillment-issue resolution', 'NI', 'NI', ['AB'], [], 'OPS', 'SharePoint: Sweet July Skin - Operations Specialist - Job Description.docx', 'JD wording: resolve fulfillment issues "before a customer has to follow up." Sits inside Nicole\'s interim OC3PL coverage. A and R both NI.'),
  ('Ecommerce & DTC', 'Amazon channel management (FBA, AWD, Seller Central)', 'NI', 'AB', ['SS'], ['DI', 'AC'], 'OPS', 'acb-thelanding: data/links.json (Sales & Commerce / Amazon Dashboard); Alvin, 2026-07-31 (marketing, wholesale and web)', 'Hub gave Amazon to Alvin; resolved to Nicole under all-channel accountability with Alvin doing the work. Inventory and inbound pipeline transition to the Ops Specialist.'),
  ('Ecommerce & DTC', 'Product detail page content and product copy', 'SS', 'SS', ['NI', 'PC', 'EH', 'IT'], ['AB', 'DI'], '', 'acb-thelanding: data/links.json (Sales & Commerce / SJS Product Copy Database); Alvin, 2026-07-31 (marketing, wholesale and web)', 'Product Copy Database is live from PLM and carries every claim, ingredient line, FAQ and Amazon title across DTC, Amazon and wholesale. Perrine and Regulatory consulted because claims on a PDP are claims. A and R both Soraya.'),

# ==== Finance ====
  ('Finance', 'Margin architecture framework and quarterly portfolio review', 'AB', 'AB', ['DI', 'NI'], [], '', '.claude/skills/sjs-margin-architect/references/framework.md:209; .claude/skills/sjs-margin-portfolio-review/SKILL.md:1', 'Framework reference plus the quarterly portfolio sweep and traffic-light report. A and R both AB.'),
  ('Finance', 'Per-SKU margin pressure-test against channel floors', 'PC', 'AB', ['SS', 'NI'], ['DI'], '', '.claude/skills/sjs-margin-pressure-test/SKILL.md:93', "Flagged as Perrine and Soraya's call to ratify, with Alvin on admin, Nicole consulting and Danielle approving."),
  ('Finance', 'Walk-away decision when a SKU breaks its channel floor', 'DI', 'AB', ['PC', 'SS', 'NI'], [], '', '.claude/skills/sjs-margin-walk-away/SKILL.md:93,105,118', 'Danielle approves on three of the four paths. Alvin carries the work on all four.'),
  ('Finance', 'SKU archetype and Standard / Acquisition designation', 'PC', 'AB', ['NI'], ['DI'], '', '.claude/skills/sjs-margin-walk-away/SKILL.md:78', 'Perrine as PD owner with Alvin on PD admin and sourcing; Nicole consults.'),
  ('Finance', 'Monthly and quarterly vendor cost rollups', 'AB', 'AB', ['IF'], ['DI'], '', '.claude/skills/regulatory-manager/SKILL.md:196; .claude/skills/purchasing-manager/SKILL.md:365; Alvin, 2026-07-31 (external partners)', 'regulatory-manager Jobs 8 and 9 read vendor_invoices directly; purchasing-manager has no rollup of its own. A and R both AB. Ironclad consulted - the rollup feeds their books.'),
  ('Finance', 'Accounts payable, bookkeeping and payroll', 'AB', 'IF', ['DI'], [], '', 'Alvin, 2026-07-31 (external partners)', 'Ironclad Finance runs AP, bookkeeping and payroll; Dan Bender is the contact. Cost-side accountability sits with Operations because the vendor-invoice pipeline and its five approval gates feed it. No longer an unowned function.'),
  ('Finance', 'Month-end close and management reporting', 'DI', 'IF', ['AB', 'NI'], ['AC'], '', 'Alvin, 2026-07-31 (external partners)', 'Ironclad Finance closes the books and produces the reporting; Dan Bender is the contact. Reporting accountability sits with the President.'),
  ('Finance', 'Annual budget and forecast consolidation', 'DI', 'IF', ['AB', 'NI', 'SS'], ['AC'], '', 'Alvin, 2026-07-31 (external partners)', 'President answers for the budget. Operations and Consumer Strategy feed the operating and channel assumptions.'),
  ('Finance', 'Inventory valuation and cost of goods', 'AB', 'IF', ['NI', 'PC'], ['DI'], '', 'Alvin, 2026-07-31 (external partners); .claude/skills/inventory-manager/SKILL.md:18', 'Cost side, so accountability sits with Operations - it flows out of purchasing, receiving and the inventory ledger. Ironclad carries it into the books.'),

# ==== People & Admin ====
  ('People & Admin', 'Hiring the Operations Specialist and the PD Project Manager Specialist', 'AB', 'NI', ['DI', 'CH'], ['AC'], '', 'decisions/log.md:52,58; context/priorities.md:3; Alvin, 2026-07-31 (external partners)', 'Both new roles report to Nicole. Decision owner recorded as Alvin, with Nicole on the two new roles once filled. Priority 1 of 2 this quarter. Calm HR runs the recruiting process once the RACI clears Danielle.'),
  ('People & Admin', 'Tool procurement, vendor renewals and shared-folder admin', 'AB', 'AB', ['NI', 'IT'], [], '', '.claude/skills/sjs-comp-intel/references/team-ownership.md:50; .claude/skills/sjs-comp-intel/references/sequencing-plan.md:12', 'Ex-Ops-Coordinator scope. Alvin carries it directly until the Operations Specialist starts. A and R both AB.'),
  ('People & Admin', 'Employee onboarding, offboarding and access deprovisioning', 'AB', 'CH', ['NI', 'DI'], [], '', '.claude/skills/asana-pd-manager/references/role-map.md:48-56; Alvin, 2026-07-31 (external partners)', 'Calm HR is the PEO and co-employer and runs the process; Alvin is the liaison and answers for it. Danielle consulted. No longer an unowned function - the departed-role-holder checklist in the PD role-map remains the internal system-side counterpart.'),
  ('People & Admin', 'Operations Specialist recruiting', 'AB', 'NI', ['DI'], ['AC'], '', "Leadership Business Review 2026-07-30 52:48-53:17; Email to Danielle 2026-07-27 'Proposed Ops Positions'", 'Prioritized first. Danielle: "we\'re going to prioritize the operations... Specialist." Reports to Nicole. Target in place before Q4. Salary band $72-90K.'),
  ('People & Admin', 'PD Specialist role definition and phased recruiting', 'AB', 'NI', ['DI'], ['AC'], '', "Leadership Business Review 2026-07-30 53:17-57:10; Email to Danielle 2026-07-27 'Proposed Ops Positions'", 'Phased in after the Ops Specialist. Danielle scopes it as "air traffic control, holding people accountable" rather than strategy or ideation, and is adding trend-forecasting language to the JD. Reports to Nicole. Salary band $75-95K.'),
  ('People & Admin', 'SOP cleanup and operational prep before new-hire onboarding', 'AB', 'NI', [], ['DI'], '', 'Leadership Business Review 2026-07-30 54:24-55:43, 1:00:32', "Danielle's condition on the hire: clean up the system first so the role can function. Nicole's action item from the review."),
  ('People & Admin', 'Employee handbook and HR policy', 'AB', 'CH', ['DI'], ['NI', 'AC'], '', 'Alvin, 2026-07-31 (external partners)', 'Calm HR drafts and maintains; Alvin is the liaison and answers for it; Danielle co-approves. Handbook is in flight as of 2026-07-30 and goes to legal review before implementation.'),
  ('People & Admin', 'Benefits administration and payroll processing', 'AB', 'CH', ['DI', 'IF'], [], '', 'Alvin, 2026-07-31 (external partners)', 'Calm HR administers as co-employer. Ironclad consulted where payroll hits the books.'),
  ('People & Admin', 'Employment compliance and separations', 'AB', 'CH', ['DI'], [], '', 'Alvin, 2026-07-31 (external partners)', 'Calm HR runs the process with outside counsel where needed. Danielle co-approves every separation.'),

# ==== IT / Systems & Data ====
  ('IT / Systems & Data', 'PLM schema, write path, audit log and Supabase wiki custody', 'AB', 'AB', ['PC'], [], '', '.claude/skills/plm-assistant/SKILL.md:292; decisions/wiki-layer-audit-2026-07-29.md:52', 'plm-assistant is the sole PLM writer and every write needs Operations sign-off. Job 0 wiki write-back has not fired since 2026-05-26. A and R both AB.'),
  ('IT / Systems & Data', 'Landing hub publish and Netlify Function maintenance', 'AB', 'AB', [], [], '', '.claude/skills/quality-status-reporter/SKILL.md:34-50; .claude/skills/quality-status-reporter/references/hub-integration.md:85', 'All hub writes go through the landing-hub-publish Function behind an Operator gate. Deploy is commit-and-push only, never Netlify CLI. A and R both AB.'),
  ('IT / Systems & Data', 'Asana project, section, custom-field and connector configuration', 'AB', 'AB', ['NI'], [], '', 'references/architecture/asana_task_contract.md:227; connections.md:5-13', 'An unresolvable role-holder is surfaced for Alvin to decide, not dropped. Seven tool domains registered; iMessage still not connected. A and R both AB.'),
  ('IT / Systems & Data', 'Skill suite authorship, audit and versioning', 'AB', 'AB', [], [], '', 'decisions/skills-architecture-tracker.md:4; decisions/log.md:31,45', 'Owner recorded as Alvin Belt across the architecture decisions. Priority 2 of 2 this quarter. A and R both AB.'),
  ('IT / Systems & Data', 'The 23 scheduled Routines and their HITL gates', 'AB', 'AB', [], ['NI'], '', 'scheduled-prompts/weekly-pd-update.md:91; scheduled-prompts/sjs-purchasing-monthly-rollup-and-snapshot.md:79', 'Nothing commits until Alvin says go. Same pattern across all 23 Routines, including the ones that fire unattended on a schedule. A and R both AB.'),
  ('IT / Systems & Data', 'RACI and role framework across Operations and PD', 'AB', 'NI', ['DI'], [], '', 'Leadership Business Review 2026-07-30 52:12-52:39', 'Alvin owns the framework, built with Nicole in the builder session, then to Danielle for final review before it goes to Calm HR to start recruiting.'),
  ('IT / Systems & Data', 'Website platform, Shopify storefront and web releases', 'DI', 'TK', ['NI', 'SS', 'EH', 'IT'], ['AB'], '', 'Alvin, 2026-07-31 (marketing, wholesale and web)', 'Teknologics is the web development partner. Danielle accountable; Nicole is the systems and tech owner; Erin and Ivy on visual design; Soraya consulted on merchandising and content; Alvin informed.'),
  ('IT / Systems & Data', 'Web and digital systems ownership, including the Teknologics engagement', 'DI', 'NI', ['TK', 'AB', 'SS'], ['AC'], '', 'Alvin, 2026-07-31 (marketing, wholesale and web)', 'Nicole is the systems and tech owner for the web and digital stack. Scoped here to web and digital rather than the whole IT function - the PLM, Asana, hub-publish and Routine rows still sit with Alvin. Confirm whether that should widen.'),
]
